[build]
  publish = "public"

[context.deploy-preview.environment]
  LIKES_CONTENT = "dummy"

[context.production.environment]
  LIKES_CONTENT = "actual"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"